// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZUMIhVArp0eDhG3L6DTStnpsf2VVUdM',
    appId: '1:651115965785:web:83621c1dde1cb7b62c3048',
    messagingSenderId: '651115965785',
    projectId: 'quis-kebangsaan',
    authDomain: 'quis-kebangsaan.firebaseapp.com',
    databaseURL: 'https://quis-kebangsaan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quis-kebangsaan.appspot.com',
    measurementId: 'G-P91Q8DVBFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjxxXYZaLLiyMegP-7gM9WjsA5gigO3tM',
    appId: '1:651115965785:android:5273b3d80e6903ce2c3048',
    messagingSenderId: '651115965785',
    projectId: 'quis-kebangsaan',
    databaseURL: 'https://quis-kebangsaan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quis-kebangsaan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOSxcDFzfH3NJ5XQ0S-5VtAToIYWSHiJ4',
    appId: '1:651115965785:ios:338d164120afadfc2c3048',
    messagingSenderId: '651115965785',
    projectId: 'quis-kebangsaan',
    databaseURL: 'https://quis-kebangsaan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quis-kebangsaan.appspot.com',
    iosClientId: '651115965785-tb0q3bht3p13n5ooi1jmrdnfuui1k846.apps.googleusercontent.com',
    iosBundleId: 'xyz.potasyyum.quisKebangsaan',
  );
}
